spring.application.name=Number-bridge

spring.output.ansi.enabled=ALWAYS


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=message

twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.phone-number=${TWILIO_PHONE_NUMBER:}
twilio.verify-service-sid=${TWILIO_VERIFY_SERVICE_SID:}
